[Desktop Entry]
Name=MediaWiki Export
Name[bg]=Изнасяне към MediaWiki
Name[bs]=MediaWiki izvoz
Name[ca]=Exportador a MediaWiki
Name[ca@valencia]=Exportació a MediaWiki
Name[cs]=Export MediaWiki
Name[da]=MediaWiki-eksport
Name[de]=MediaWiki-Export
Name[el]=Εξαγωγή στα MediaWiki
Name[en_GB]=MediaWiki Export
Name[es]=Exportar a MediaWiki
Name[et]=MediaWiki eksport
Name[ga]=Easpórtáil MediaWiki
Name[gl]=Exportar a MediaWiki
Name[hu]=MediaWiki exportálás
Name[is]=MediaWiki útflutningur
Name[it]=Esportazione a MediaWiki
Name[km]=នាំចេញ​វីគី​មេឌៀ​
Name[nb]=MediaWiki-eksport
Name[nl]=Naar MediaWiki exporteren
Name[pl]=Eksport do MediaWiki
Name[pt]=Exportação para o MediaWiki
Name[pt_BR]=Exportar para o MediaWiki
Name[ro]=Export MediaWiki
Name[ru]=Экспорт на Викисклад
Name[sl]=Izvoz MediaWiki
Name[sv]=Export till MediaWiki
Name[uk]=Експорт до MediaWiki
Name[x-test]=xxMediaWiki Exportxx
Name[zh_CN]=MediaWiki导出
Name[zh_TW]=MediaWiki 匯出
Comment=A tool to export images to a remote MediaWiki web service
Comment[bg]=Инструмент за изнасяне на изображения към отдалечена уеб-услуга MediaWiki
Comment[bs]=Alat za izvoz slika na udaljeni MediaWiki web servis
Comment[ca]=Una eina per exportar imatges al servei web remot MediaWiki
Comment[ca@valencia]=Una eina per exportar imatges al servei web remot MediaWiki
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby MediaWiki
Comment[da]=Et værktøj til at eksportere billeder til en ekstern MediaWiki webtjeneste
Comment[de]=Ein Werkzeug, um Bilder zu einem entfernten MediaWiki-Webdienst zu exportieren.
Comment[el]=Εργαλείο εξαγωγής εικόνων σε μια απομακρυσμένη υπηρεσία ιστού MediaWiki
Comment[en_GB]=A tool to export images to a remote MediaWiki web service
Comment[es]=Una herramienta para exportar imágenes al servicio web remoto de MediaWiki
Comment[et]=Tööriist piltide eksportimiseks MediaWiki veebiteenusesse
Comment[ga]=Uirlis a easpórtálann íomhánna go seirbhís Ghréasáin MediaWiki i gcéin
Comment[gl]=Unha ferramenta para exportar imaxes a un servizo web MediaWiki remoto
Comment[hu]=Egy eszköz képek exportálásához egy távoli MediaWiki webszolgáltatásba
Comment[is]=Verkfæri til að senda myndir á fjarlæga MediaWiki vefþjónustu
Comment[it]=Uno strumento per esportare immagini al servizio Web remoto MediaWiki
Comment[km]=ឧបករណ៍​ត្រូវ​នាំចេញ​រូបភាព​ទៅ​សេវា​បណ្ដាញ​វីគី​មេឌៀ​ពី​ចម្ងាយ​
Comment[nb]=Et verktøy for å eksportere bilder til en fjern MediaWiki-nettjeneste
Comment[nl]=Een hulpmiddel om afbeeldingen naar een MediaWiki-webservice te exporteren
Comment[pl]=Narzędzie do eksportowania obrazów do zdalnej usługi sieciowej MediaWiki
Comment[pt]=Uma ferramenta de exportação de imagens para um serviço Web remoto do MediaWiki
Comment[pt_BR]=Uma ferramenta para exportar imagens para um serviço remoto da Internet MediaWiki
Comment[ro]=O unealtă de exportat imagini pe serviciul web MediaWiki
Comment[ru]=Инструмент для экспорта изображений в веб-службу MediaWiki
Comment[sl]=Orodje za izvoz slik v oddaljeno spletno storitev MediaWiki
Comment[sv]=Ett verktyg för att exportera bilder till en MediaWiki fjärrwebbtjänst
Comment[uk]=Інструмент для експорту зображень до віддаленої служби MediaWiki
Comment[x-test]=xxA tool to export images to a remote MediaWiki web servicexx
Comment[zh_TW]=匯出影像到遠端 MediaWiki 網頁服務的工具
Icon=wikimedia
ServiceTypes=KIPI/Plugin
Type=Service
X-KDE-Library=kipiplugin_wikimedia
author=Guillaume Hormiere, hormiere dot guillaume at gmail dot com
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
