[Desktop Entry]
UntranslatedGenericName=Flickr/23
Name=Flickr/23
Name[ca]=Flickr/23
Name[ca@valencia]=Flickr/23
Name[cs]=Flickr/23
Name[de]=Flickr/23
Name[el]=Flickr/23
Name[en_GB]=Flickr/23
Name[es]=Flickr/23
Name[fr]=Flickr/23
Name[gl]=Flickr/23
Name[id]=Flickr/23
Name[is]=Flickr/23
Name[it]=Flickr/23
Name[nl]=Flickr/23
Name[pl]=Flickr/23
Name[pt]=Flickr/23
Name[ru]=Flickr/23
Name[sl]=Flickr/23
Name[sv]=Flickr/23
Name[tr]=Flickr/23
Name[uk]=Flickr/23
Name[x-test]=xxFlickr/23xx
Comment=A tool to export images to remote Flickr and 23 web services.
Comment[ca]=Una eina per exportar les imatges als serveis web remots Flickr i 23.
Comment[ca@valencia]=Una eina per exportar les imatges als serveis web remots Flickr i 23.
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby Flickr a 23.
Comment[de]=Ein Werkzeug, um Bilder zum Flickr- oder 23- Webdienst zu exportieren.
Comment[el]=Εργαλείο εξαγωγής εικόνων στις απομακρυσμένες υπηρεσίες ιστού Flickr και 23.
Comment[en_GB]=A tool to export images to remote Flickr and 23 web services.
Comment[es]=Una herramienta para exportar imágenes a los servicios web remotos de Flickr y 23.
Comment[fr]=Un outil pour l'export d'images vers les services en ligne Flickr et 23.
Comment[gl]=Unha ferramenta para exportar imaxes a servizos web remotos Flickr ou 23.
Comment[id]=Sebuah alat untuk mengekspor citra ke layanan web Flickr dan 23 jarak jauh.
Comment[is]=Verkfæri til að senda myndir á fjarlægar Flickr og 23 vefþjónustur.
Comment[it]=Uno strumento per esportare immagini ai servizi web remoti Flickr e 23.
Comment[nl]=Een hulpmiddel om afbeeldingen naar een Flickr- en 23-webservice op afstand te exporteren.
Comment[pl]=Narzędzie do eksportowania obrazów do zdalnych usług sieciowych Flickr i 23.
Comment[pt]=Uma ferramenta para exportar imagens para os serviços Web remotos do Flickr e 23.
Comment[ru]=Инструмент для экспорта изображений в веб-службы Flickr и 23
Comment[sl]=Orodje za izvoz slik v oddaljeni spletni storitvi Flickr in 23.
Comment[sv]=Ett verktyg för att exportera bilder till webbtjänsterna Flickr eller 23.
Comment[tr]=Resimleri Flickr ve 23 web servisine aktarmak için bir araç.
Comment[uk]=Інструмент для експорту зображень до віддалених служб Flickr та 23.
Comment[x-test]=xxA tool to export images to remote Flickr and 23 web services.xx
Type=Service
Icon=kipi-flickr
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_flickr
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_LIB_SO_CUR_VERSION}
author=Vardhman Jain, vardhman at gmail dot com
