#ifndef SEPIAPHOTOEFFECT_GLOBAL_H
#define SEPIAPHOTOEFFECT_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QtPlugin>

#if defined(SEPIAPHOTOEFFECT_LIBRARY)
#  define SEPIAPHOTOEFFECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SEPIAPHOTOEFFECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SEPIAPHOTOEFFECT_GLOBAL_H
