[Desktop Entry]
Encoding=UTF-8
Name=VideoSlideShow
Name[da]=Video-diasshow
Name[el]=VideoSlideShow
Name[is]=Vídeóskyggnusýning
Name[it]=Presentazione video
Name[nl]=Diavoorstelling met video
Name[pt]=Apresentação de Vídeo
Name[pt_BR]=Apresentação de vídeo
Name[sl]=VideoSlideShow
Name[sv]=Videobildspel
Name[uk]=Відеопоказ слайдів
Name[x-test]=xxVideoSlideShowxx
Comment=A tool to export images as Video Slide Show
Comment[da]=Et værktøj til at eksportere billeder som et video-diasshow
Comment[el]=Εργαλείο εξαγωγής εικόνων ως παρουσίαση διαφανειών βίντεο
Comment[is]=Verkfæri til að flytja myndir út vídóskyggnusýningu
Comment[it]=Uno strumento per esportare immagini come presentazione video
Comment[nl]=Een hulpmiddel voor het exporteren van afbeeldingen als diavoorstelling met video
Comment[pt]=Uma ferramenta para exportar imagens como uma apresentação de vídeo
Comment[pt_BR]=Uma ferramenta para exportar imagens como uma apresentação de vídeo
Comment[sl]=Orodje za izvoz slik v video predstavitev
Comment[sv]=Ett verktyg för att exportera bilder som ett videobildspel
Comment[uk]=Інструмент для експортування зображень у форматі відеопоказу слайдів
Comment[x-test]=xxA tool to export images as Video Slide Showxx
Type=Service
Icon=media-record
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_videoslideshow
author=A Janardhan Reddy, annapareddyjanardhanreddy at gmail dot com
X-KIPI-ReqFeatures=
X-KIPI-PluginCategories=Tools
