[Desktop Entry]
UntranslatedGenericName=GoogleDrive Export
Name=GoogleDrive Export
Name[de]=GoogleDrive-Export
Name[gl]=Exportación a GoogleDrive
Name[nl]=Exporteren naar GoogleDrive
Name[pt]=Exportação para o Google Drive
Name[pt_BR]=Exportar para o GoogleDrive
Name[uk]=Експорт до GoogleDrive
Name[x-test]=xxGoogleDrive Exportxx
Comment=A tool to export images to a remote GoogleDrive web service
Comment[de]=Ein Werkzeug, um Bilder zu einem entfernten GoogleDrive-Webdienst zu exportieren.
Comment[gl]=Unha ferramenta para exportar imaxes a un servizo web GoogleDrive remoto
Comment[nl]=Een hulpmiddel om afbeeldingen naar een GoogleDrive-webservice te exporteren
Comment[pt]=Uma ferramenta para exportar imagens para o serviço Web remoto Google Drive
Comment[pt_BR]=Uma ferramenta para exportar imagens para um serviço da Internet GoogleDrive
Comment[uk]=Інструмент для експорту зображень до віддаленої служби GoogleDrive
Comment[x-test]=xxA tool to export images to a remote GoogleDrive web servicexx
Type=Service
Icon=kipi-googledrive
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_googledrive
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Saurabh Patel, saurabhpatel7717@gmail.com
