[Desktop Entry]
UntranslatedGenericName=GoogleDrive Export
Name=Google Drive Export
Name[ca]=Exportador a Google Drive
Name[cs]=Export do Google Drive
Name[da]=Eksport til Google Drev
Name[de]=„Google Drive“-Export
Name[gl]=Exportación a Google Drive
Name[it]=Esportazione a Google Drive
Name[nl]=Exporteren naar Google Drive
Name[pt]=Exportação para o Google Drive
Name[pt_BR]=Exportar para o Google Drive
Name[sk]=Google Drive Export
Name[sl]=Izvoz v Google Drive
Name[sv]=Export till Google Drive
Name[tr]=Google Drive Aktarımı
Name[uk]=Експорт до Google Drive
Name[x-test]=xxGoogle Drive Exportxx
Comment=A tool to export images to a remote Google Drive web service
Comment[ca]=Una eina per exportar imatges al servei web remot Google Drive
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby Google Drive
Comment[da]=Et værktøj til at eksportere billeder til en ekstern Google Drive-webtjeneste
Comment[de]=Ein Werkzeug, um Bilder zu einem entfernten „Google Drive“-Webdienst zu exportieren.
Comment[gl]=Unha ferramenta para exportar imaxes a un servizo web Google Drive remoto
Comment[it]=Uno strumento per esportare immagini al servizio Web remoto Google Drive
Comment[nl]=Een hulpmiddel om afbeeldingen naar een Google Drive-webservice te exporteren
Comment[pt]=Uma ferramenta para exportar imagens para o serviço Web remoto Google Drive
Comment[pt_BR]=Uma ferramenta para exportar imagens para um serviço da Internet Google Drive
Comment[sl]=Orodje za izvoz slik v oddaljeno spletno storitev Google Drive
Comment[sv]=Ett verktyg för att exportera bilder till en Google Drive fjärrwebbtjänst
Comment[tr]=Resimleri uzak bir Google Drive web hizmetine aktarmak için bir araç
Comment[uk]=Інструмент для експорту зображень до віддаленої служби Google Drive
Comment[x-test]=xxA tool to export images to a remote Google Drive web servicexx
Type=Service
Icon=kipi-googledrive
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_googledrive
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Saurabh Patel, saurabhpatel7717@gmail.com
