[Desktop Entry]
Encoding=UTF-8
Name=DLNAExport
Name[cs]=DLNAExport
Name[da]=DLNAExport
Name[el]=DLNAExport
Name[et]=DLNA eksport
Name[hu]=DLNA exportálás
Name[is]=DLNA-útflutningur
Name[it]=Esportazione a DLNA
Name[nl]=DLNA-export
Name[pl]=EksportDoDLNA
Name[pt]=DLNAExport
Name[pt_BR]=Exportar para DLNA
Name[sl]=DLNAExport
Name[sv]=Export till DLNA
Name[uk]=Експорт до DLNA
Name[x-test]=xxDLNAExportxx
Name[zh_TW]=DLNA匯出
Comment=A tool to export collection on DLNA network service
Comment[cs]=Nástroj pro export kolekce do síťové služby DLNA
Comment[da]=Et værktøj til at eksportere samling på DLNA-netværkstjenesten
Comment[el]=Εργαλείο εξαγωγής συλλογής σε δικτυακή υπηρεσία DLNA
Comment[et]=Tööriist kogu eksportimiseks DLNA võrguteenusesse
Comment[hu]=Egy eszköz gyűjtemények exportálásához DLNA hálózati szolgáltatásba
Comment[is]=Tól til að flytja myndasöfn yfir í DLNA netþjónustu
Comment[it]=Uno strumento per esportare raccolte sul servizio in rete DLNA
Comment[nl]=Een hulpmiddel om een verzameling naar een DLNA-netwerk te exporteren
Comment[pl]=Narzędzie do eksportowania zbioru do usługi sieciowej DLNA
Comment[pt]=Uma ferramenta para exportar a colecção num serviço de rede DLNA
Comment[pt_BR]=Uma ferramenta para exportar a coleção para um serviço de rede DLNA
Comment[sl]=Orodje za izvoz zbirk na omrežno storitev DLNA
Comment[sv]=Ett verktyg för att exportera bilder till en DLNA nätverkstjänst
Comment[uk]=Інструмент для експорту збірок до служби DLNA у мережі
Comment[x-test]=xxA tool to export collection on DLNA network servicexx
Comment[zh_TW]=匯出 DLNA 網路服務上的收藏的工具
Type=Service
Icon=dlna
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_dlnaexport
author=Smit Mehta, smit dot meh at gmail dot com
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
X-KIPI-ReqFeatures=
