[Desktop Entry]
UntranslatedGenericName=BatchProcessImages
Name=BatchProcessImages
Name[ast]=BatchProcessImages
Name[bg]=Пакетна обработка на изображения
Name[bs]=BatchProcessImages
Name[ca]=BatchProcessImages
Name[ca@valencia]=BatchProcessImages
Name[cs]=Dávkové zpracování obrázků
Name[da]=Batchbehandling af billeder
Name[de]=Bilder-Stapelverarbeitung
Name[el]=Ομαδική επεξεργασία εικόνων
Name[en_GB]=BatchProcessImages
Name[es]=Procesamiento en lote de imágenes
Name[et]=Piltide pakktöötlus
Name[eu]=Irudien batch prozesua
Name[fi]=BatchProcessImages
Name[fr]=Envoi d'images par courrier électronique
Name[ga]=BatchProcessImages
Name[gl]=BatchProcessImages
Name[hu]=Képek kötegelt feldolgozása
Name[is]=BatchProcessImages
Name[it]=Elaborazione automatica delle immagini
Name[ja]=BatchProcessImages
Name[km]=BatchProcessImages
Name[lv]=BatchProcessImages
Name[nb]=Satsvis bildebehandling
Name[nds]=Bild-Stapelverarbeiden
Name[nl]=AfbeeldingenVerwerken
Name[pa]=BatchProcessImages
Name[pl]=WsadowePrzetwarzanieObrazów
Name[pt]=Processamento em Lote de Imagens
Name[pt_BR]=Processamento de imagens em lote
Name[ro]=Procesare de imagini în serie
Name[ru]=Пакетная обработка изображений
Name[sk]=Dávkové spracovanie obrázkov
Name[sl]=BatchProcessImages
Name[sq]=Procedim i Menjëhershëm i Imazheve
Name[sv]=Bakgrundsbehandling av bilder
Name[th]=ประมวลผลกลุ่มภาพ
Name[tr]=Çoklu Resim İşleme
Name[uk]=Пакетна обробка зображень
Name[x-test]=xxBatchProcessImagesxx
Name[zh_CN]=批处理图像
Name[zh_TW]=批次處理影像
Comment=A tool to batch process images
Comment[ca]=Una eina per a processar imatges per lots
Comment[cs]=Nástroj pro dávkové zpracování obrázků
Comment[da]=Et værktøj til batchbehandling af billeder
Comment[de]=Ein Werkzeug zur Stapelverarbeitung von Bildern
Comment[en_GB]=A tool to batch process images
Comment[it]=Uno strumento per elaborare automaticamente le immagini
Comment[nl]=Een hulpmiddel voor het bewerken van afbeeldingen in bulk
Comment[pl]=Narzędzie do wsadowego przetwarzania obrazów
Comment[pt]=Uma ferramenta para processar imagens em lote
Comment[pt_BR]=Uma ferramenta para processar imagens em lote
Comment[sk]=Nástroj na dávkové spracovanie obrázkov
Comment[sl]=Orodje za paketno obdelavo slik
Comment[sv]=Ett verktyg för att behandla bilder i bakgrunden
Comment[uk]=Інструмент для пакетної обробки зображень
Comment[x-test]=xxA tool to batch process imagesxx
Icon=borderimages
ServiceTypes=KIPI/Plugin
Type=Service
X-KDE-Library=kipiplugin_batchprocessimages
X-KIPI-PluginCategories=Batch
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Gilles Caulier, caulier dot gilles at gmail dot com
