[Desktop Entry]
Comment=A tool to create KML files with geolocated images
Icon=applications-development-web
UntranslatedGenericName=KMLExport
Name=KMLExport
Name[bg]=Изнасяне в KML
Name[bs]=KMLExport
Name[ca]=Exportador a KML
Name[ca@valencia]=Exportador a KML
Name[cs]=KMLExport
Name[da]=KMLExport
Name[de]=KMLExport
Name[el]=KMLExport
Name[en_GB]=KMLExport
Name[es]=KMLExport
Name[et]=KML-i eksport
Name[fr]=Exportation « KML »
Name[ga]=KMLExport
Name[gl]=KMLExport
Name[hu]=KML exportálás
Name[is]=KMLÚtflutningur
Name[it]=Esportazione a KML
Name[km]=KMLExport
Name[nb]=KMLeksport
Name[nl]=KMLExport
Name[pl]=EksportDoKML
Name[pt]=KMLExport
Name[pt_BR]=Exportar para KML
Name[ro]=KMLExport
Name[ru]=Экспорт в KML
Name[sk]=KMLExport
Name[sl]=KMLExport
Name[sv]=Export till KML
Name[tr]=KMLExport
Name[uk]=KMLExport
Name[x-test]=xxKMLExportxx
Name[zh_CN]=KML导出
Name[zh_TW]=KML 匯出
ServiceTypes=KIPI/Plugin
Type=Service
X-KDE-Library=kipiplugin_kmlexport
X-KIPI-ReqFeatures=ImagesHasTime
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Gilles Caulier, caulier dot gilles at gmail dot com
