[Desktop Entry]
UntranslatedGenericName=Google Services Export
Name=Google Services Export
Name[ca]=Exportador a Google Services
Name[cs]=Export služeb Google
Name[de]=„Google Services“-Export
Name[nl]=Exporteren naar Google Services
Name[pt]=Exportação para os Serviços do Google
Name[pt_BR]=Exportar para os Serviços do Google
Name[sv]=Export till Google-tjänster
Name[uk]=Експорт до служб Google
Name[x-test]=xxGoogle Services Exportxx
Comment=A tool to export images to a remote Google Services web service
Comment[ca]=Una eina per exportar imatges al servei web remot Google Services
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby Google Services
Comment[de]=Ein Werkzeug, um Bilder zu einem entfernten „Google Services“-Webdienst zu exportieren.
Comment[nl]=Een hulpmiddel om afbeeldingen naar een Google Services-webservice te exporteren
Comment[pt]=Uma ferramenta para exportar imagens para um dos serviços Web remotos da Google
Comment[pt_BR]=Ferramenta para exportar imagens para os Serviços do Google
Comment[sv]=Ett verktyg för att exportera bilder till en Google-tjänster fjärrwebbtjänst
Comment[uk]=Інструмент для експорту зображень до віддаленої служби Google
Comment[x-test]=xxA tool to export images to a remote Google Services web servicexx
Type=Service
Icon=kipi-googledrive
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_googleservices
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Saurabh Patel, saurabhpatel7717 at gmail dot com
