[Desktop Entry]
UntranslatedGenericName=Google Services Export
Name=Google Services Export
Name[bs]=Google Services izvoz
Name[ca]=Exportador a Google Services
Name[ca@valencia]=Exportador a Google Services
Name[cs]=Export do Google Services
Name[da]=Eksport til Google Drev
Name[de]=„Google Services“-Export
Name[el]=Εξαγωγή στο Google Services
Name[en_GB]=Google Services Export
Name[es]=Exportar a Google Services
Name[fi]=Google Services -vienti
Name[gl]=Exportación a Google Services
Name[hu]=Google Services exportálás
Name[is]=Google Services útflutningur
Name[it]=Esportazione a Google Services
Name[nb]=Google Services eksport
Name[nl]=Exporteren naar Google Services
Name[pl]=Eksportuj do Dysku Google
Name[pt]=Exportação para o Google Services
Name[pt_BR]=Exportar para o Google Services
Name[ru]=Экспорт на Диск Google
Name[sk]=Google Services Export
Name[sl]=Izvoz v Google Services
Name[sv]=Export till Google Services
Name[tr]=Google Services Aktarımı
Name[uk]=Експорт до Google Services
Name[x-test]=xxGoogle Services Exportxx
Name[zh_TW]=Google 雲端硬碟匯出
Comment=A tool to export images to a remote Google Services web service
Comment[bs]=Alat za izvoz slika na udaljeni Google Services web servis
Comment[ca]=Una eina per exportar imatges al servei web remot Google Services
Comment[ca@valencia]=Una eina per exportar imatges al servei web remot Google Services
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby Google Services
Comment[da]=Et værktøj til at eksportere billeder til en ekstern Google Services-webtjeneste
Comment[de]=Ein Werkzeug, um Bilder zu einem entfernten „Google Services“-Webdienst zu exportieren.
Comment[el]=Εργαλείο εξαγωγής εικόνων σε μια υπηρεσία ιστού του Google Services
Comment[en_GB]=A tool to export images to a remote Google Services web service
Comment[es]=Una herramienta para exportar imágenes al servicio web remoto de Google Services
Comment[fi]=Kuvien vienti Google Services -verkkopalveluun
Comment[gl]=Unha ferramenta para exportar imaxes a un servizo web Google Services remoto
Comment[hu]=Egy eszköz képek exportálásához egy távoli Google Services webszolgáltatásba
Comment[is]=Verkfæri til að senda myndir á fjarlæga Google Services vefþjónustu
Comment[it]=Uno strumento per esportare immagini al servizio Web remoto Google Services
Comment[nb]=Et verktøy for å eksportere bilder til en fjern Google Services-nettjeneste
Comment[nl]=Een hulpmiddel om afbeeldingen naar een Google Services-webservice te exporteren
Comment[pl]=Narzędzie do eksportowania obrazów do zdalnej usługi sieciowej Dysku Google
Comment[pt]=Uma ferramenta para exportar imagens para o serviço Web remoto Google Services
Comment[pt_BR]=Ferramenta para exportar imagens para o Google Services
Comment[ru]=Инструмент для экспорта изображений на Диск Google
Comment[sk]=Nástroj na export obrázkov na vzdialenú službu Google Services
Comment[sl]=Orodje za izvoz slik v oddaljeno spletno storitev Google Services
Comment[sv]=Ett verktyg för att exportera bilder till en Google Services fjärrwebbtjänst
Comment[tr]=Resimleri uzak bir Google Services web hizmetine aktarmak için bir araç
Comment[uk]=Інструмент для експорту зображень до віддаленої служби Google Services
Comment[x-test]=xxA tool to export images to a remote Google Services web servicexx
Comment[zh_TW]=匯出影像到遠端 Google 雲端硬碟網頁服務的工具
Type=Service
Icon=kipi-googledrive
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_googleservices
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Saurabh Patel, saurabhpatel7717 at gmail dot com
