#ifndef GRAYSCALEPHOTOEFFECT_GLOBAL_H
#define GRAYSCALEPHOTOEFFECT_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QtPlugin>

#if defined(GRAYSCALEPHOTOEFFECT_LIBRARY)
#  define GRAYSCALEPHOTOEFFECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRAYSCALEPHOTOEFFECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAYSCALEPHOTOEFFECT_GLOBAL_H
