[Desktop Entry]
UntranslatedGenericName=Facebook Export
Name=Facebook Export
Name[ca]=Exportador al Facebook
Name[ca@valencia]=Exportador al Facebook
Name[cs]=Export do Facebooku
Name[de]=Facebook-Export
Name[es]=Exportar a Facebook
Name[fr]=Export vers Facebook
Name[id]=Facebook Export
Name[it]=Esportazione a Facebook
Name[nl]=Facebook-export
Name[pl]=Eksport do Facebooka
Name[pt]=Exportação para o Facebook
Name[sv]=Facebook export
Name[uk]=Експорт до Facebook
Name[x-test]=xxFacebook Exportxx
Name[zh_CN]=Facebook 导出
Comment=A tool to export images to a remote Facebook web service
Comment[ca]=Una eina per exportar les imatges a un servei web remot Facebook
Comment[ca@valencia]=Una eina per exportar les imatges a un servei web remot Facebook
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby Facebook
Comment[es]=Una herramienta para exportar imágenes al servicio web remoto de Facebook
Comment[fr]=Outil pour exporter des images vers le service en ligne Facebook
Comment[id]=Sebuah alat untuk mengekspor gambar ke layanan web Facebook jarak jauh
Comment[it]=Uno strumento per esportare immagini al servizio web remoto Facebook
Comment[nl]=Een hulpmiddel om afbeeldingen naar een Facebook-webservice te exporteren
Comment[pl]=Narzędzie do eksportowania obrazów do zdalnej usługi sieciowej Facebooka
Comment[pt]=Uma ferramenta para exportar imagens para o serviço Web remoto do Facebook
Comment[sv]=Ett verktyg för att exportera bilder till en Facebook webbtjänst
Comment[uk]=Інструмент для експортування зображень до віддаленої служби Facebook
Comment[x-test]=xxA tool to export images to a remote Facebook web servicexx
Type=Service
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_facebook
Icon=kipi-facebook
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_LIB_SO_CUR_VERSION}
author=Luka Renko, lure at kubuntu dot org
