// This file is generated by kconfig_compiler from photoframeseditor.kcfg.
// All changes you do to this file will be lost.
#ifndef KIPIPHOTOFRAMESEDITOR_PFECONFIGSKELETON_H
#define KIPIPHOTOFRAMESEDITOR_PFECONFIGSKELETON_H

#include <kconfigskeleton.h>
#include <kdebug.h>

#include <kglobalsettings.h>
#include <settings/PFEConfig.h>
namespace KIPIPhotoFramesEditor {

class PFEConfigSkeleton : public KConfigSkeleton
{
  public:

    static PFEConfigSkeleton *self();
    ~PFEConfigSkeleton();

    /**
      Set Embed full-sized imaged.
    */
    static
    void setEmbedImages( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "EmbedImages" ) ))
        self()->mEmbedImages = v;
    }

    /**
      Get Embed full-sized imaged.
    */
    static
    bool embedImages()
    {
      return self()->mEmbedImages;
    }

    /**
      Set Horizontal distance
    */
    static
    void setHorizontalGrid( double v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "HorizontalGrid" ) ))
        self()->mHorizontalGrid = v;
    }

    /**
      Get Horizontal distance
    */
    static
    double horizontalGrid()
    {
      return self()->mHorizontalGrid;
    }

    /**
      Set Vertical distance
    */
    static
    void setVerticalGrid( double v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "VerticalGrid" ) ))
        self()->mVerticalGrid = v;
    }

    /**
      Get Vertical distance
    */
    static
    double verticalGrid()
    {
      return self()->mVerticalGrid;
    }

  protected:
    PFEConfigSkeleton();
    friend class PFEConfigSkeletonHelper;


    // Saving
    bool mEmbedImages;

    // View
    double mHorizontalGrid;
    double mVerticalGrid;

  private:
};

}

#endif

