[Desktop Entry]
Encoding=UTF-8
Name=Photivo Integration
Name[da]=Photivo-integration
Name[el]=Ενσωμάτωση Photivo
Name[hu]=Photivo integráció
Name[is]=Innbygging Photivo
Name[it]=Integrazione di Photivo
Name[nl]=Photivo-integratie
Name[pl]=Integracja Photivo
Name[pt]=Integração com o Photivo
Name[pt_BR]=Integração com o Photivo
Name[sl]=Podpora za Photivo
Name[sv]=Integrering av Photivo
Name[uk]=Інтеграція Photivo
Name[x-test]=xxPhotivo Integrationxx
Name[zh_TW]=Photivo 整合
Comment=Integration of the Photivo RAW-Processor
Comment[da]=Integration af RAW-behandleren Photivo
Comment[el]=Ενσωμάτωση του RAW-επεξεργαστή Photivo
Comment[is]=Innbygging Photivo RAW-meðhöndlunar í kerfið
Comment[it]=Integrazione dell'elaboratore RAW Photivo
Comment[nl]=Integratie van de Photivo RAW-processor
Comment[pl]=Integracja programu przetwarzającego RAW Photivo
Comment[pt]=Integração com o Processador RAW Photivo
Comment[pt_BR]=Integração com o Processador RAW Photivo
Comment[sl]=Podpora za obdelovalnik RAW Photivo
Comment[sv]=Integrering av Photivo bearbetning av obehandlade bilder
Comment[uk]=Інтеграція програми для обробки цифрових негативів Photivo
Comment[x-test]=xxIntegration of the Photivo RAW-Processorxx
Comment[zh_TW]=與 Photivo RAW-Processor 整合
Type=Service
Icon=photivo
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_photivointegration
author=Dominic Lyons, domlyons at googlemail dot com
X-KIPI-PluginCategories=Tools
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
X-KIPI-ReqFeatures=
