#ifndef BLURPHOTOEFFECT_GLOBAL_H
#define BLURPHOTOEFFECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLURPHOTOEFFECT_LIBRARY)
#  define BLURPHOTOEFFECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLURPHOTOEFFECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLURPHOTOEFFECT_GLOBAL_H
