[Desktop Entry]
UntranslatedGenericName=Dropbox Export
Name=Dropbox Export
Name[de]=Dropbox-Export
Name[gl]=Exportación a Dropbox
Name[nl]=Exporteren naar Dropbox
Name[pt_BR]=Exportar para o Dropbox
Name[sv]=Export till Dropbox
Name[uk]=Експорт до Dropbox
Name[x-test]=xxDropbox Exportxx
Comment=A tool to export images to a remote Dropbox web service
Comment[de]=Ein Werkzeug, um Bilder zu einem entfernten Dropbox-Webdienst zu exportieren.
Comment[gl]=Unha ferramenta para exportar imaxes a un servizo web Dropbox remoto
Comment[nl]=Een hulpmiddel om afbeeldingen naar een Dropbox-webservice te exporteren
Comment[pt_BR]=Uma ferramenta para exportar imagens para um serviço remoto da Internet Dropbox
Comment[sv]=Ett verktyg för att exportera bilder till en Dropbox fjärrwebbtjänst
Comment[uk]=Інструмент для експорту зображень до віддаленої служби Dropbox
Comment[x-test]=xxA tool to export images to a remote Dropbox web servicexx
Type=Service
Icon=kipi-dropbox
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_dropbox
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Saurabh Patel, saurabhpatel7717@gmail.com
