[Desktop Entry]
UntranslatedGenericName=Dropbox Export
Name=Dropbox Export
Name[ca]=Exportador a Dropbox
Name[cs]=Export do Dropboxu
Name[da]=Eksport til Dropbox
Name[de]=Dropbox-Export
Name[gl]=Exportación a Dropbox
Name[it]=Esportazione a Dropbox
Name[nb]=Dropbox eksport
Name[nl]=Exporteren naar Dropbox
Name[pt]=Exportação para o Dropbox
Name[pt_BR]=Exportar para o Dropbox
Name[sk]=Dropbox Export
Name[sl]=Izvoz v Dropbox
Name[sv]=Export till Dropbox
Name[tr]=Dropbox Aktarımı
Name[uk]=Експорт до Dropbox
Name[x-test]=xxDropbox Exportxx
Comment=A tool to export images to a remote Dropbox web service
Comment[ca]=Una eina per exportar imatges al servei web remot Dropbox
Comment[cs]=Nástroj pro export obrázků do vzdálené webové služby Dropbox
Comment[da]=Et værktøj til at eksportere billeder til en ekstern Dropbox-webtjeneste
Comment[de]=Ein Werkzeug, um Bilder zu einem entfernten Dropbox-Webdienst zu exportieren.
Comment[gl]=Unha ferramenta para exportar imaxes a un servizo web Dropbox remoto
Comment[it]=Uno strumento per esportare immagini al servizio Web remoto Dropbox
Comment[nb]=Et verktøy for å eksportere bilder til en fjern Dropbox-nettjeneste
Comment[nl]=Een hulpmiddel om afbeeldingen naar een Dropbox-webservice te exporteren
Comment[pt]=Uma ferramenta para exportar imagens para o serviço Web remoto Dropbox
Comment[pt_BR]=Uma ferramenta para exportar imagens para um serviço remoto da Internet Dropbox
Comment[sl]=Orodje za izvoz slik v oddaljeno spletno storitev Dropbox
Comment[sv]=Ett verktyg för att exportera bilder till en Dropbox fjärrwebbtjänst
Comment[tr]=Resimleri uzak bir Dropbox web hizmetine aktarmak için bir araç
Comment[uk]=Інструмент для експорту зображень до віддаленої служби Dropbox
Comment[x-test]=xxA tool to export images to a remote Dropbox web servicexx
Type=Service
Icon=kipi-dropbox
ServiceTypes=KIPI/Plugin
X-KDE-Library=kipiplugin_dropbox
X-KIPI-PluginCategories=Export
X-KIPI-BinaryVersion=${KIPI_SO_VERSION}
author=Saurabh Patel, saurabhpatel7717@gmail.com
