.\" Author: Paul Telford <pxt@debian.org>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with the Debian GNU/Linux system; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307 USA
.TH kipidcrawclient "1" "November 2003"
.SH NAME
kipidcrawclient \- RAW file converter for digikam
.SH SYNOPSIS
kipidcrawclient 
.SH DESCRIPTION
.B kipidcrawclient
is a file converter for digital cameras which support the RAW format.
This program is used as part of the \fBRaw Converter\fP plugin for
\fBKipi(1)\fP.  You should not need to run this executable directly.
.PP
Complete Kipi documentation can be found in docbook format in
/usr/share/doc/kde/HTML/<lang>/kipi/ on this system.
.SH AUTHOR
Renchi Raju <renchi@pooh.tam.uiuc.edu>
.PP
This manual page was written by Paul Telford <pxt@debian.org> for
the \fBDebian\fP system (but may be used by others).
